// Shapes exchanged between the API and the dashboard.
import type { Repeat } from "./reminderSchedule";
import type { RelatedKind } from "./staff";

export type EmailState = "needs_decision" | "task" | "snoozed" | "dismissed" | "elsewhere";
export type Priority = "low" | "normal" | "high" | "urgent";

// One step of a task's checklist (user request 2026-10-07).
export type ChecklistItem = { id: string; text: string; done: boolean };

// A link kept with a reminder, e.g. the Google Sheet to fill in (user request 2026-10-07). Empty name = show
// the kind of file ("Google Sheet") instead.
export type ReminderLink = { url: string; name: string };
export type TaskView = "today" | "upcoming" | "overdue" | "nodate" | "all" | "completed" | "any" | "reports" | "waiting";
// Tasks due between two dates (inclusive), open and done.
export type RangeTasks = { from: string; to: string; today: string; tasks: Task[] };

// Linked tasks of an email: how many are open or done, and whether an open one is overdue.
export type ThreadTaskInfo = { open: number; done: number; overdue: boolean };

export type Thread = {
  id: string;
  gmailThreadId: string;
  accountEmail: string | null;
  subject: string;
  fromName: string | null;
  fromEmail: string | null;
  snippet: string;
  lastMessageAt: string;
  messageCount: number;
  unread: boolean;
  state: EmailState;
  snoozedUntil: string | null;
  hasNewActivity: boolean;
  stateChangedAt: string;
  task: ThreadTaskInfo | null;
  // Sender is hidden from Pending in Settings > Mail (the email still shows under All emails).
  muted: boolean;
  // The user's own Gmail labels on the conversation (IDs; names and colours come from /labels).
  labelIds: string[];
  // The other section (label) it went to; still set when a new reply brought it back to Pending.
  sectionLabelId: string | null;
};

export type Label = { id: string; name: string; backgroundColor: string | null; textColor: string | null };

export type MutedSender = { id: string; pattern: string; hidden: number };

export type Task = {
  id: string;
  title: string;
  notes: string;
  dueDate: string | null;
  dueTime: string | null;
  priority: Priority;
  status: "open" | "done";
  // Gmail labels: the email's own labels for a task from an email (changing them changes Gmail), or the
  // task's WorkDesk-only labels for one without an email.
  labelIds: string[];
  checklist: ChecklistItem[];
  // Waiting for a reply since (null = not waiting), and the day a reply is expected by (optional).
  waitingSince: string | null;
  replyBy: string | null;
  // What it is about (Staff page): an employee, a designation or the general office (null = not set).
  relatedKind: RelatedKind | null;
  relatedId: string | null;
  // Made by WorkDesk itself, e.g. Pension papers 12 months before retirement (user request 2026-10-08).
  madeBySystem: boolean;
  completedAt: string | null;
  createdAt: string;
  // Set for tasks generated by a recurring report.
  report: { reportId: string; periodId: string; name: string; label: string; links: ReminderLink[] } | null;
  thread: Pick<
    Thread,
    "id" | "gmailThreadId" | "accountEmail" | "subject" | "fromName" | "fromEmail" | "hasNewActivity"
  > | null;
};

export type AuditEvent = {
  id: string;
  entityType: "email" | "task" | "report" | "sync";
  entityId: string | null;
  action: string;
  summary: string;
  detail: { subject?: string; title?: string } | null;
  createdAt: string;
  // Current state of the email, so a dismissal can be undone from History.
  emailState: EmailState | null;
};

export type Me = {
  email: string;
  name: string | null;
  title: string | null;
  picture: string | null;
  demo: boolean;
  today: string;
  timezone: string;
  account: { email: string; lastSyncAt: string | null; lastSyncError: string | null; pending: number; canMarkRead: boolean } | null;
};

export type Summary = {
  today: string;
  counts: {
    pendingEmails: number;
    unreadPending: number;
    dueToday: number;
    overdue: number;
    dueTomorrow: number;
    newActivity: number;
    completedThisWeek: number;
    openTasks: number;
    upcoming: number;
    completedTotal: number;
    // Report periods not yet submitted: due in the next 30 days, and already overdue.
    reportsUpcoming: number;
    reportsOverdue: number;
    // Open tasks generated by reports.
    reportTasks: number;
    // Tasks waiting for a reply.
    waiting: number;
    // Home's "Pending jobs" card: open tasks that aren't waiting or made by a reminder, and reminder dates due
    // today or overdue (user request 2026-10-07).
    jobTasks: number;
    remindersDue: number;
    // Increments shown in Due Today (Staff, user request 2026-10-07): this month's from the 20th, earlier ones always.
    incrementsDue: number;
    // Temporary employees' contracts ending within 7 days or already past (user request 2026-10-08).
    contractsEnding: number;
  };
  incrementsDue: IncrementDue[];
  contractsEnding: ContractEnding[];
  overdue: Task[];
  dueToday: Task[];
  dueTomorrow: Task[];
  newActivity: Task[];
  pendingEmails: Thread[];
  recentlyCompleted: Task[];
};

// A reminder's occurrence (old reminders also have reporting-period rows, labelled "Sep 2026").
export type ReportPeriod = {
  id: string;
  label: string;
  dueDate: string;
  // "submitted" = done.
  status: "pending" | "submitted";
  submittedAt: string | null;
  taskId: string | null;
};

// A reminder (stored as a report).
export type Report = {
  id: string;
  name: string;
  notes: string;
  repeat: Repeat;
  startDate: string;
  dueTime: string | null;
  endDate: string | null;
  dueDay: number;
  leadDays: number;
  priority: Priority;
  active: boolean;
  links: ReminderLink[];
  relatedKind: RelatedKind | null;
  relatedId: string | null;
  // Created occurrences, newest first.
  periods: ReportPeriod[];
};

// --- Email viewer (content read from Gmail on demand; never stored in the database) ---

export type EmailAttachment = {
  partId: string;
  filename: string;
  mimeType: string;
  size: number;
  // Set for images embedded in the HTML body (referenced as cid:...).
  contentId: string | null;
  inline: boolean;
};

export type EmailMessageContent = {
  id: string;
  fromName: string | null;
  fromEmail: string | null;
  to: string;
  cc: string;
  date: string;
  subject: string;
  html: string | null;
  text: string | null;
  attachments: EmailAttachment[];
};

export type EmailContent = { threadId: string; version: number; messages: EmailMessageContent[] };

// Staff page (user request 2026-10-07).
export type Designation = { id: string; name: string; sortOrder: number };
export type Employee = {
  id: string;
  name: string;
  designationId: string | null;
  // Permanent or temporary (user request 2026-10-07); engagedTill only for temporary ones.
  permanent: boolean;
  engagedTill: string | null;
  // Temporary ones only: engagement ("contract" | "daily_wage" | "temporary" | ""), type, contract days, pay per day.
  engagement: string;
  typeId: string | null;
  contractDays: number | null;
  payPerDay: number | null;
  pen: string;
  phone: string;
  email: string;
  dateOfBirth: string | null;
  category: string;
  joinedServiceOn: string | null;
  joinedOfficeOn: string | null;
  nextIncrementOn: string | null;
  retiresOn: string | null;
  payScale: string;
  probationDeclaredOn: string | null;
  address: string;
  notes: string;
  // Left the office on (null = still here). Hidden from the pickers, kept for old tasks.
  leftOn: string | null;
};
// A type of temporary employee (HMC, NHM…), user request 2026-10-07.
export type EmployeeType = { id: string; name: string; sortOrder: number };
export type StaffList = { designations: Designation[]; types: EmployeeType[]; employees: Employee[] };

// An employee's increment shown in Home's Due Today (user request 2026-10-07).
export type IncrementDue = { employeeId: string; name: string; designation: string | null; due: string };

// A temporary employee's contract ending, shown in Home's Due Today (user request 2026-10-08). days = the
// contract period (null: not given, so Renew needs it set on the employee first).
// An employee retiring within 12 months (user request 2026-10-08), with the Pension papers task WorkDesk made
// for them (null: not made yet, e.g. already past the date, or deleted).
export type RetiringEmployee = { employeeId: string; name: string; designation: string | null; retiresOn: string; task: Task | null };

export type ContractEnding = { employeeId: string; name: string; designation: string | null; end: string; days: number | null };

// File register (user request 2026-10-07): a physical file and/or an e-file. efileNumber "" = e-file not created yet.
export type OfficeFile = { id: string; subject: string; physical: boolean; efileNumber: string; notes: string; updatedAt: string };
