// Shapes exchanged between the API and the dashboard.

export type EmailState = "needs_decision" | "task" | "snoozed" | "dismissed";
export type Priority = "low" | "normal" | "high" | "urgent";
export type TaskView = "today" | "upcoming" | "overdue" | "nodate" | "all" | "completed" | "any" | "reports";
// Tasks due between two dates (inclusive), open and done.
export type RangeTasks = { from: string; to: string; today: string; tasks: Task[] };

export type Category = { id: string; name: string; sortOrder: number };

// Linked tasks of an email: how many are open or done, and whether an open one is overdue.
export type ThreadTaskInfo = { open: number; done: number; overdue: boolean };

export type Thread = {
  id: string;
  gmailThreadId: string;
  accountEmail: string | null;
  subject: string;
  fromName: string | null;
  fromEmail: string | null;
  snippet: string;
  lastMessageAt: string;
  messageCount: number;
  unread: boolean;
  state: EmailState;
  snoozedUntil: string | null;
  hasNewActivity: boolean;
  categoryId: string | null;
  stateChangedAt: string;
  task: ThreadTaskInfo | null;
};

export type Task = {
  id: string;
  title: string;
  notes: string;
  dueDate: string | null;
  dueTime: string | null;
  priority: Priority;
  status: "open" | "done";
  categoryId: string | null;
  completedAt: string | null;
  createdAt: string;
  // Set for tasks generated by a recurring report.
  report: { reportId: string; periodId: string; name: string; label: string } | null;
  thread: Pick<
    Thread,
    "id" | "gmailThreadId" | "accountEmail" | "subject" | "fromName" | "fromEmail" | "hasNewActivity"
  > | null;
};

export type AuditEvent = {
  id: string;
  entityType: "email" | "task" | "report" | "sync";
  entityId: string | null;
  action: string;
  summary: string;
  detail: { subject?: string; title?: string } | null;
  createdAt: string;
  // Current state of the email, so a dismissal can be undone from History.
  emailState: EmailState | null;
};

export type Me = {
  email: string;
  name: string | null;
  title: string | null;
  picture: string | null;
  demo: boolean;
  today: string;
  timezone: string;
  account: { email: string; lastSyncAt: string | null; lastSyncError: string | null; pending: number; canMarkRead: boolean } | null;
};

export type Summary = {
  today: string;
  counts: {
    pendingEmails: number;
    unreadPending: number;
    dueToday: number;
    overdue: number;
    dueTomorrow: number;
    newActivity: number;
    completedThisWeek: number;
    openTasks: number;
    upcoming: number;
    completedTotal: number;
    // Report periods not yet submitted: due in the next 30 days, and already overdue.
    reportsUpcoming: number;
    reportsOverdue: number;
    // Open tasks generated by reports.
    reportTasks: number;
  };
  overdue: Task[];
  dueToday: Task[];
  dueTomorrow: Task[];
  newActivity: Task[];
  pendingEmails: Thread[];
  recentlyCompleted: Task[];
};

export type Frequency = "monthly" | "quarterly" | "half_yearly" | "annual";

export type ReportPeriod = {
  id: string;
  periodStart: string;
  periodEnd: string;
  label: string;
  dueDate: string;
  status: "pending" | "submitted";
  submittedAt: string | null;
  taskId: string | null;
};

export type Report = {
  id: string;
  name: string;
  notes: string;
  frequency: Frequency;
  dueDay: number;
  dueMonthOffset: number;
  yearStartMonth: number;
  leadDays: number;
  priority: Priority;
  categoryId: string | null;
  responsible: string | null;
  firstPeriodStart: string;
  active: boolean;
  // Generated periods, newest first.
  periods: ReportPeriod[];
};

// --- Email viewer (content read from Gmail on demand; never stored in the database) ---

export type EmailAttachment = {
  partId: string;
  filename: string;
  mimeType: string;
  size: number;
  // Set for images embedded in the HTML body (referenced as cid:...).
  contentId: string | null;
  inline: boolean;
};

export type EmailMessageContent = {
  id: string;
  fromName: string | null;
  fromEmail: string | null;
  to: string;
  cc: string;
  date: string;
  subject: string;
  html: string | null;
  text: string | null;
  attachments: EmailAttachment[];
};

export type EmailContent = { threadId: string; version: number; messages: EmailMessageContent[] };
